#!/bin/bash
# files-workspace-setup.script
# $1 username
# $2 launch delay in integer seconds
# ------------------------------------------------------------------------------------------------------


case "${1:-"ellathecat"}" in
    (ellathecat)
        delay=${2:-1}
        files-workspace.script 59:4 $(( delay +  2 )) &
        files-workspace.script 55:2 $(( delay + 10 )) &
        files-workspace.script 51:1 $(( delay + 14 )) &
        ;;
    (*)
        speak-ng "Create your $USER case in $(basename $0)"
        ;;
esac

# ------------------------------------------------------------------------------------------------------
#
# Done.
#
